server:
  address: "0.0.0.0"
  port: 8080

intervals:
  fast: 1s
  slow: 1m

disk:
  ignore_fs:
    - tmpfs
    - proc
    - sysfs
    - overlay
    - squashfs

network:
  ignore_interfaces:
    - lo
    - docker*
    - br-*
    - veth*
